# Build settings
remote_theme: yaoyao-liu/minimal-light

# Basic Information 
title: Sisi Peng, PhD MS MPH
position: Research Scientist
affiliation: UCLA Department of Communication
email: s.peng@ucla.edu

# Links
linkedin: https://www.linkedin.com/in/sisipeng

# Images
avatar: ./assets/img/Sisi-Headshot.jpg

