# Build settings
remote_theme: yaoyao-liu/minimal-light

# Basic Information 
title: Sisi Peng, MPH MS
position: PhD Candidate
affiliation: UCLA Department of Communication
email: s.peng@ucla.edu

# Links
linkedin: https://www.linkedin.com/in/sisipeng
