# Build settings
remote_theme: yaoyao-liu/minimal-light

# Basic Information 
title: Sisi Peng
position: Ph.D. Candidate
affiliation: UCLA
email: s.peng@ucla.edu

# Links
linkedin: https://www.linkedin.com/in/sisipeng
